In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
object = pd.read_pickle('sparse')

In [3]:
movies = pd.DataFrame(object)

In [4]:
movies

MovieID     1      2      3      4      5      6      7      8      9      \
CustomerID                                                                  
6             NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
7             NaN    NaN    NaN    NaN    NaN    NaN    NaN    5.0    NaN   
8             NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
10            NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
25            NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
2649404       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649409       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649421       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649426       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649429       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

MovieID     10     ...  17761  17762  17763  17764  17765  17766  17767  \
CustomerID         ...                                                    
6             NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
7             NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
8             NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
10            NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
25            NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...           ...  ...    ...    ...    ...    ...    ...    ...    ...   
2649404       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649409       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649421       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649426       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649429       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

MovieID     17768  17769  17770  
CustomerID                       
6             NaN    NaN    NaN  
7             NaN    NaN    NaN  
8             NaN    NaN    NaN  
10            NaN    NaN    NaN  
25            NaN    NaN    NaN  
...           ...    ...    ...  
2649404       NaN    NaN    NaN  
2649409       NaN    NaN    NaN  
2649421       NaN    NaN    NaN  
2649426       NaN    NaN    NaN  
2649429       NaN    NaN    NaN  

[3701937 rows x 17770 columns]

In [5]:
movies = movies.fillna(0)

In [6]:
#movies.to_pickle("sparse2") 

In [33]:
nparr = np.load('sparse2', allow_pickle=True, encoding="bytes")

In [34]:
print(nparr)

MovieID     1      2      3      4      5      6      7      8      9      \
CustomerID                                                                  
6             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7             0.0    0.0    0.0    0.0    0.0    0.0    0.0    5.0    0.0   
8             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
10            0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
25            0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
2649404       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649409       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649421       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649426       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649429       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

In [9]:
terms = pd.read_csv('movie_titles.txt', sep='\t', encoding = "ISO-8859-1", header=None)

In [10]:
terms = terms.iloc[:,:3]

In [11]:
terms = terms.iloc[:,2:]

In [12]:
terms

2
0                                        Dinosaur Planet
1                             Isle of Man TT 2004 Review
2                                              Character
3                           Paula Abdul's Get Up & Dance
4                               The Rise and Fall of ECW
...                                                  ...
17765  Where the Wild Things Are and Other Maurice Se...
17766                  Fidel Castro: American Experience
17767                                              Epoch
17768                                        The Company
17769                                       Alien Hunter

[17770 rows x 1 columns]

In [13]:
import kMeans
import importlib

In [14]:
#movies[:10]

In [15]:
smallmov = movies[:5000]

In [16]:
movie_arr = np.array(smallmov)

In [27]:
print(movie_arr)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
centroids_tfidf, clusters_tfidf = kMeans.kMeans(movie_arr, 5, kMeans.distCosine, kMeans.randCent)

In [18]:
print(centroids_tfidf)

[[0.00242915 0.         0.0097166  ... 0.         0.         0.        ]
 [0.00348432 0.         0.06852497 ... 0.         0.         0.        ]
 [0.01405405 0.00540541 0.01621622 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.01830443 0.         0.0105973  ... 0.         0.         0.        ]]


In [19]:
centroids = pd.DataFrame(centroids_tfidf, columns=terms)

In [20]:
centroids

(Dinosaur Planet,)  (Isle of Man TT 2004 Review,)  (Character,)  \
0            0.002429                       0.000000      0.009717   
1            0.003484                       0.000000      0.068525   
2            0.014054                       0.005405      0.016216   
3            0.000000                       0.000000      0.000000   
4            0.018304                       0.000000      0.010597   

   (Paula Abdul's Get Up & Dance,)  (The Rise and Fall of ECW,)   (Sick,)  \
0                         0.000810                     0.004858  0.000000   
1                         0.000000                     0.000000  0.000000   
2                         0.007568                     0.004324  0.036757   
3                         0.000000                     0.013815  0.006376   
4                         0.001927                     0.020231  0.000963   

   (8 Man,)  (What the #$*! Do We Know!?,)  (Class of Nuke 'Em High 2,)  \
0       0.0                       0.065587                          0.0   
1       0.0                       0.221835                          0.0   
2       0.0                       0.134054                          0.0   
3       0.0                       0.028693                          0.0   
4       0.0                       0.079961                          0.0   

   (Fighter,)  ...  (Levity,)  (Gattaca,)  (Interiors,)  \
0         0.0  ...        0.0         0.0           0.0   
1         0.0  ...        0.0         0.0           0.0   
2         0.0  ...        0.0         0.0           0.0   
3         0.0  ...        0.0         0.0           0.0   
4         0.0  ...        0.0         0.0           0.0   

   (Shakespeare in Love,)  (Godzilla's Revenge,)  \
0                     0.0                    0.0   
1                     0.0                    0.0   
2                     0.0                    0.0   
3                     0.0                    0.0   
4                     0.0                    0.0   

   (Where the Wild Things Are and Other Maurice Sendak Stories,)  \
0                                                0.0               
1                                                0.0               
2                                                0.0               
3                                                0.0               
4                                                0.0               

   (Fidel Castro: American Experience,)  (Epoch,)  (The Company,)  \
0                                   0.0       0.0             0.0   
1                                   0.0       0.0             0.0   
2                                   0.0       0.0             0.0   
3                                   0.0       0.0             0.0   
4                                   0.0       0.0             0.0   

   (Alien Hunter,)  
0              0.0  
1              0.0  
2              0.0  
3              0.0  
4              0.0  

[5 rows x 17770 columns]

In [21]:
print(clusters_tfidf)

[[4.         0.17669098]
 [4.         0.12647031]
 [3.         0.36934376]
 ...
 [0.         0.54017001]
 [3.         0.28168605]
 [0.         0.58475017]]


In [22]:
def top_terms(n, centroids, clusters):
    for i in range(len(centroids)):
        term_list = pd.DataFrame(terms)
        clusters = pd.DataFrame(clusters)
        term_indexs = np.array(clusters.index[clusters.iloc[:,0] == i])
        termvals = pd.concat([term_list, pd.DataFrame(centroids[i])], axis=1)
        #print(termvals)
        termvals_new = termvals.iloc[term_indexs]
        termvals_new.columns = ['Term','Value']
        #print(termvals_new)
        termvals_new.sort_values(by='Value', axis=0, inplace=True, ascending=False)
        #print(termvals_new)
        
        
        
        print('Cluster' + str(i+1) + ':')
        print('Number of Users: ' + str(len(term_indexs)))
        print('Top Films:')
        print("\n")
        top_term = termvals_new.head(n)
        for term in top_term.iterrows():
            print("Movie: ", term[1][0], term[1][1])
            #print("\n")
        print("\n")
    
top_terms(20, centroids_tfidf, clusters_tfidf)

Cluster1:
Number of Users: 1235
Top Films:


Movie:  Man on Fire 1.9246963562753037
Movie:  Mean Girls 0.9951417004048583
Movie:  Along Came Polly 0.968421052631579
Movie:  Coach Carter 0.8259109311740891
Movie:  The Recruit 0.8242914979757086
Movie:  Eternal Sunshine of the Spotless Mind 0.7319838056680162
Movie:  Bend It Like Beckham 0.682591093117409
Movie:  The Wedding Planner 0.5554655870445344
Movie:  The Matrix: Revolutions 0.3757085020242915
Movie:  Harold and Kumar Go to White Castle 0.3481781376518219
Movie:  The Mummy 0.24210526315789474
Movie:  Bridget Jones's Diary 0.2388663967611336
Movie:  Brother Bear (Theatrical Widescreen Version) 0.22753036437246962
Movie:  Fried Green Tomatoes 0.16761133603238867
Movie:  The Hitchhiker's Guide to the Galaxy 0.1659919028340081
Movie:  Lilo and Stitch 0.15708502024291499
Movie:  Life as a House 0.1522267206477733
Movie:  Being John Malkovich 0.1522267206477733
Movie:  Spartan 0.14898785425101216
Movie:  Dogma 0.1125506072874494


Clus

<ipython-input-22-9c0c39ca8580>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  termvals_new.sort_values(by='Value', axis=0, inplace=True, ascending=False)
<ipython-input-22-9c0c39ca8580>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  termvals_new.sort_values(by='Value', axis=0, inplace=True, ascending=False)
<ipython-input-22-9c0c39ca8580>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  termvals_new.sort_values(by='Value', axis

In [23]:
from sklearn.metrics import completeness_score, homogeneity_score

In [24]:
completeness = completeness_score(smallmov.iloc[:,0], clusters_tfidf.T[0])
homogeneity = homogeneity_score(smallmov.iloc[:,0], clusters_tfidf.T[0])

print('Completeness of Cluster: '+  str(completeness))
print('Homogeneity of Clusters: '+ str(homogeneity))

Completeness of Cluster: 0.0009705869541405151
Homogeneity of Clusters: 0.09397706560849574


In [25]:
#test = np.array(movies[5000:10000])

In [26]:
#smallmov.append(test)