In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
object = pd.read_pickle('sparse')

In [3]:
movies = pd.DataFrame(object)

In [4]:
movies

MovieID     1      2      3      4      5      6      7      8      9      \
CustomerID                                                                  
6             NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
7             NaN    NaN    NaN    NaN    NaN    NaN    NaN    5.0    NaN   
8             NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
10            NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
25            NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
2649404       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649409       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649421       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649426       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649429       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

MovieID     10     ...  17761  17762  17763  17764  17765  17766  17767  \
CustomerID         ...                                                    
6             NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
7             NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
8             NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
10            NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
25            NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...           ...  ...    ...    ...    ...    ...    ...    ...    ...   
2649404       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649409       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649421       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649426       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2649429       NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

MovieID     17768  17769  17770  
CustomerID                       
6             NaN    NaN    NaN  
7             NaN    NaN    NaN  
8             NaN    NaN    NaN  
10            NaN    NaN    NaN  
25            NaN    NaN    NaN  
...           ...    ...    ...  
2649404       NaN    NaN    NaN  
2649409       NaN    NaN    NaN  
2649421       NaN    NaN    NaN  
2649426       NaN    NaN    NaN  
2649429       NaN    NaN    NaN  

[3701937 rows x 17770 columns]

In [5]:
movies = movies.fillna(0)

In [6]:
#movies.to_pickle("sparse2") 

In [7]:
nparr = np.load('sparse2', allow_pickle=True, encoding="bytes")

In [8]:
print(nparr)

MovieID     1      2      3      4      5      6      7      8      9      \
CustomerID                                                                  
6             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7             0.0    0.0    0.0    0.0    0.0    0.0    0.0    5.0    0.0   
8             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
10            0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
25            0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
2649404       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649409       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649421       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649426       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2649429       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

In [9]:
terms = pd.read_csv('movie_titles.txt', sep='\t', encoding = "ISO-8859-1", header=None)

In [10]:
terms = terms.iloc[:,:3]

In [11]:
terms = terms.iloc[:,2:]

In [12]:
terms

2
0                                        Dinosaur Planet
1                             Isle of Man TT 2004 Review
2                                              Character
3                           Paula Abdul's Get Up & Dance
4                               The Rise and Fall of ECW
...                                                  ...
17765  Where the Wild Things Are and Other Maurice Se...
17766                  Fidel Castro: American Experience
17767                                              Epoch
17768                                        The Company
17769                                       Alien Hunter

[17770 rows x 1 columns]

In [13]:
import kMeans
import importlib

In [14]:
from sklearn.cluster import KMeans

In [15]:
kmeans = KMeans(n_clusters = 7)

In [16]:
smallmov = movies[:5000]

In [17]:
movie_arr = np.array(smallmov)

In [18]:
kmeans.fit(movie_arr)

KMeans(n_clusters=7)

In [19]:
kmeans.labels_.shape

(5000,)

In [20]:
kmeans.cluster_centers_

array([[ 2.04081633e-02, -4.33680869e-19,  1.78571429e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.27388535e-02, -6.50521303e-19,  1.04083409e-17, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.73472348e-18, -6.50521303e-19,  2.46913580e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 9.33333333e-02, -4.33680869e-19,  1.20000000e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.42465753e-03, -6.50521303e-19,  9.13242009e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.21739130e-03,  8.69565217e-03,  3.13043478e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [21]:
kmeans.cluster_centers_[0]

array([ 2.04081633e-02, -4.33680869e-19,  1.78571429e-01, ...,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00])

In [22]:
kmeans.cluster_centers_[1]

array([ 1.27388535e-02, -6.50521303e-19,  1.04083409e-17, ...,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00])

In [23]:
clust1 = kmeans.cluster_centers_[0]

In [24]:
test = pd.DataFrame(clust1,terms)

In [25]:
test = test.sort_values(by=[0],ascending=False)

In [26]:
np.set_printoptions(precision=2,suppress=True)

In [27]:
def top_movies(df, k):
    for mov in range(0,k):
        print(df.index[mov], df[0][mov])

In [28]:
top_movies(test, 15)

('American Beauty',) 4.198979591836735
('Being John Malkovich',) 3.8367346938775513
('Pirates of the Caribbean: The Curse of the Black Pearl',) 3.7653061224489788
('Reservoir Dogs',) 3.7551020408163263
('Eternal Sunshine of the Spotless Mind',) 3.2653061224489797
('Jaws',) 3.193877551020407
('High Fidelity',) 3.173469387755102
('Kill Bill: Vol. 2',) 3.096938775510204
('Clerks',) 3.0765306122448974
('A Beautiful Mind',) 3.0510204081632644
('Dogma',) 2.887755102040816
('The Professional',) 2.8214285714285716
('Chasing Amy',) 2.586734693877551
('Bend It Like Beckham',) 2.5663265306122445
('Lock',) 2.540816326530612


In [29]:
def print_clust(kmeans, k):
    for cluster in range(0,k):
        clust = kmeans.cluster_centers_[cluster]
        #print(clust)
        #print(clust.shape)
        sortDF = pd.DataFrame(clust,terms)
        sortDF = sortDF.sort_values(by=[0],ascending=False)
        print("Top movies in Cluster", cluster+1)
        top_movies(sortDF, 15)
        print("")

In [30]:
print_clust(kmeans,7)

Top movies in Cluster 1
('American Beauty',) 4.198979591836735
('Being John Malkovich',) 3.8367346938775513
('Pirates of the Caribbean: The Curse of the Black Pearl',) 3.7653061224489788
('Reservoir Dogs',) 3.7551020408163263
('Eternal Sunshine of the Spotless Mind',) 3.2653061224489797
('Jaws',) 3.193877551020407
('High Fidelity',) 3.173469387755102
('Kill Bill: Vol. 2',) 3.096938775510204
('Clerks',) 3.0765306122448974
('A Beautiful Mind',) 3.0510204081632644
('Dogma',) 2.887755102040816
('The Professional',) 2.8214285714285716
('Chasing Amy',) 2.586734693877551
('Bend It Like Beckham',) 2.5663265306122445
('Lock',) 2.540816326530612

Top movies in Cluster 2
('Pirates of the Caribbean: The Curse of the Black Pearl',) 4.022292993630573
('Man on Fire',) 3.5764331210191087
('Lethal Weapon',) 3.500000000000001
('The Bourne Supremacy',) 3.48407643312102
('X2: X-Men United',) 3.2866242038216553
('Speed',) 3.0254777070063685
('50 First Dates',) 2.9554140127388546
('American Beauty',) 2.9426

Making a sample user to test:
Users will rate random movies they have seen upon launching our app

In [63]:
test_user = np.zeros(17770)

In [64]:
print(test_user)

[0. 0. 0. ... 0. 0. 0.]


In [65]:
test_user.shape

(17770,)

In [66]:
test_user[0]

0.0

In [67]:
user_scores = np.random.randint(17769, size=40)

In [68]:
user_scores

array([10243, 11177,  2240, 12049,  4172, 16203,  2699,  2855,  4118,
       12885,   209,  7627, 14568,  4542,  4923,  6463, 10596, 13332,
       13353,  7124,  3517,  1683, 10869,  6273,  9621,  5557,  3819,
        2872, 12033,  2447,  3076,  8913, 11901,  6437,  5320, 14177,
        5209, 11500, 11485, 11089])

In [69]:
for movidx in user_scores:
    test_user[movidx] = np.random.randint(1,6)

In [70]:
test_user.shape

(17770,)

In [71]:
test_user =test_user.reshape(-1, 1).T

In [72]:
test_user.shape

(1, 17770)

In [73]:
kmeans.predict(test_user)

array([3])

So we can recommend the top movies from cluster 3 for this user: